# Generated by Django 5.0.2 on 2024-03-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarteirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('bairro', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bairro', to='quart.bairro')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('tb', 'tb'), ('out', 'outros')], max_length=6)),
                ('lado', models.IntegerField()),
                ('quarteirao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quarteirao', to='quart.quarteirao')),
                ('rua', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rua', to='quart.rua')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
