# Generated by Django 5.0.2 on 2024-03-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarteirao',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Quarteiroe'},
        ),
    ]
