# Generated by Django 5.0.2 on 2024-03-18 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quart', '0003_alter_quarteirao_options_alter_imovel_complemento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiraBoletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quart', models.CharField(max_length=4)),
                ('num_imoveis', models.CharField(max_length=4)),
                ('extrato', models.CharField(max_length=4)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bairro_lira', to='quart.bairro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_lira', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiraBoletimDado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(blank=True, max_length=6)),
                ('tipo', models.CharField(choices=[('tb', 'tb'), ('out', 'outros')], max_length=6)),
                ('a1', models.IntegerField(default=0)),
                ('a2', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('d1', models.IntegerField(default=0)),
                ('d2', models.IntegerField(default=0)),
                ('boletim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lira_boletim', to='quart.liraboletim')),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quart_lira', to='quart.quarteirao')),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rua_lira', to='quart.rua')),
            ],
        ),
    ]
