# Generated by Django 5.0.2 on 2024-04-01 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quart', '0004_liraboletim_liraboletimdado'),
    ]

    operations = [
        migrations.AddField(
            model_name='liraboletim',
            name='id_boletim',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='liraboletimdado',
            name='id_dado',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
