# Generated by Django 5.0.2 on 2024-04-03 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quart', '0006_remove_liraboletim_id_remove_liraboletimdado_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarteirao',
            name='bairro',
        ),
        migrations.AlterField(
            model_name='liraboletimdado',
            name='quart',
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name='liraboletim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liraboletim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='liraboletimdado',
            name='numero',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Imovel',
        ),
        migrations.DeleteModel(
            name='Quarteirao',
        ),
    ]
