# Generated by Django 5.0.2 on 2024-04-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quart', '0007_remove_quarteirao_bairro_alter_liraboletimdado_quart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liraboletim',
            name='chefe',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chefe', to=settings.AUTH_USER_MODEL),
        ),
    ]
