# Generated by Django 5.0.2 on 2024-04-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quart', '0009_liraboletim_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('ciclo', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-ano', '-ciclo'],
            },
        ),
        migrations.AddField(
            model_name='liraboletim',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciclo_boletim', to='quart.ciclo'),
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_bairro', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('bairro_nome', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bairros', to='quart.bairro')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciclo_indice', to='quart.ciclo')),
            ],
            options={
                'ordering': ['bairro_nome'],
            },
        ),
    ]
